### ISSUE TITLE
Piracy

### ISSUE THREAD

**Issue by riziles** [CultureCounter/xgrams#1]
Somebody stole your intellectual property! https://xgrams-fork.vercel.app/ 

Oh, wait it was me. Let me know if you want me to take it down. It was so cool I thought the world should see it.

**Comment by riziles** [comment]
Check out my new site!

![image](https://user-images.githubusercontent.com/98712531/223311685-a1812b38-b8a3-453c-bf1a-0290e1b5a3c2.png)

**Comment by dirk-bester** [comment]
Thank you for teaching me how easy vercel deployment is. I was expecting a 1 day research project! Not 3 minutes flat. That was so incredible! The official one is now at https://xgrams.vercel.app/ with a working stopwatch!

I have documented the code lineages it builds on as well if you feel like hacking around on your fork. So it is MIT. If it was scratch made I would probably do [Do What the Fuck You Want to Public License](http://www.wtfpl.net/)

**Comment by riziles** [comment]
Ha ha! I don't know if "teaching" is the right word, but I'll take it! Not sure how Vercel makes any money, but I hope they keep supporting Svelte development and let me deploy stuff for free on their blazing faster servers. 

BTW, this project is awesome and so much fun.
